// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SistemaRefuerzo.Infrastructure.Persistence;

#nullable disable

namespace SistemaRefuerzo.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260823215410_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SistemaRefuerzo.Domain.Entities.Alumno", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Grado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Alumnos");
                });

            modelBuilder.Entity("SistemaRefuerzo.Domain.Entities.Docente", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Docentes");
                });

            modelBuilder.Entity("SistemaRefuerzo.Domain.Entities.EjercicioRecomendado", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PreguntaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RecomendacionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RecomendacionId");

                    b.ToTable("EjerciciosRecomendados");
                });

            modelBuilder.Entity("SistemaRefuerzo.Domain.Entities.Evaluacion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlumnoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TemaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoId");

                    b.HasIndex("TemaId");

                    b.ToTable("Evaluaciones");
                });

            modelBuilder.Entity("SistemaRefuerzo.Domain.Entities.OpcionPregunta", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("EsCorrecta")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PreguntaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("PreguntaId");

                    b.ToTable("OpcionesPregunta");
                });

            modelBuilder.Entity("SistemaRefuerzo.Domain.Entities.Pregunta", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Enunciado")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("NivelDificultad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TemaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TemaId");

                    b.ToTable("Preguntas");
                });

            modelBuilder.Entity("SistemaRefuerzo.Domain.Entities.Recomendacion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaGeneracion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("ResultadoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Retroalimentacion")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("TemasPorReforzar")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ResultadoId")
                        .IsUnique();

                    b.ToTable("Recomendaciones");
                });

            modelBuilder.Entity("SistemaRefuerzo.Domain.Entities.Regla", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<string>("DescripcionConclusion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DescripcionCondicion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("NombreClaseRegla")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("Prioridad")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Reglas");
                });

            modelBuilder.Entity("SistemaRefuerzo.Domain.Entities.RespuestaAlumno", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("EsCorrecta")
                        .HasColumnType("boolean");

                    b.Property<Guid>("EvaluacionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OpcionSeleccionadaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PreguntaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EvaluacionId");

                    b.ToTable("RespuestasAlumno");
                });

            modelBuilder.Entity("SistemaRefuerzo.Domain.Entities.Resultado", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EvaluacionId")
                        .HasColumnType("uuid");

                    b.Property<int>("FallosConsecutivos")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCalculo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Puntaje")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EvaluacionId")
                        .IsUnique();

                    b.ToTable("Resultados");
                });

            modelBuilder.Entity("SistemaRefuerzo.Domain.Entities.Tema", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Temas");
                });

            modelBuilder.Entity("SistemaRefuerzo.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("ContrasenaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("CorreoElectronico")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SistemaRefuerzo.Domain.Entities.EjercicioRecomendado", b =>
                {
                    b.HasOne("SistemaRefuerzo.Domain.Entities.Recomendacion", null)
                        .WithMany("EjerciciosRecomendados")
                        .HasForeignKey("RecomendacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SistemaRefuerzo.Domain.Entities.OpcionPregunta", b =>
                {
                    b.HasOne("SistemaRefuerzo.Domain.Entities.Pregunta", null)
                        .WithMany("Opciones")
                        .HasForeignKey("PreguntaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SistemaRefuerzo.Domain.Entities.RespuestaAlumno", b =>
                {
                    b.HasOne("SistemaRefuerzo.Domain.Entities.Evaluacion", null)
                        .WithMany("Respuestas")
                        .HasForeignKey("EvaluacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SistemaRefuerzo.Domain.Entities.Evaluacion", b =>
                {
                    b.Navigation("Respuestas");
                });

            modelBuilder.Entity("SistemaRefuerzo.Domain.Entities.Pregunta", b =>
                {
                    b.Navigation("Opciones");
                });

            modelBuilder.Entity("SistemaRefuerzo.Domain.Entities.Recomendacion", b =>
                {
                    b.Navigation("EjerciciosRecomendados");
                });
#pragma warning restore 612, 618
        }
    }
}
